# Generated by Django 4.0.4 on 2022-04-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_car', to='company.vehicle'),
        ),
    ]
