# Generated by Django 4.0.4 on 2022-04-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_carcompany_dealer_carcompany_manufacture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcompany',
            old_name='Manufacture',
            new_name='manufacture',
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100),
        ),
    ]
